#ifndef MINIPROYECTO_CONFIGS_H
#define MINIPROYECTO_CONFIGS_H

#define MATRIX_SIZE 30
#define PLANTS_EXPAND_PROB 0.3
#define CICLOS 20


#define INITIAL_PLANTS 5
#define INITIAL_HERBIVORES 20
#define INITIAL_CARNIVORES 5


#endif //MINIPROYECTO_CONFIGS_H
