#ifndef MINIPROYECTO_CONFIGS_H
#define MINIPROYECTO_CONFIGS_H

#define MATRIX_SIZE 60
#define PLANTS_EXPAND_PROB 0.3
#define CICLOS 50000


#define INITIAL_PLANTS 30
#define INITIAL_HERBIVORES 25
#define INITIAL_CARNIVORES 15

#define ENERGY_PLANTS 3
#define ENERGY_HERBIVORES 8
#define ENERGY_CARNIVORES 8


#endif //MINIPROYECTO_CONFIGS_H
