#ifndef MINIPROYECTO_CONFIGS_H
#define MINIPROYECTO_CONFIGS_H



#define MAX_PLANTS 20
#define MAX_HERBIVORES 10
#define MAX_CARNIVORES 5
#define MATRIX_SIZE 10
#define PLANTS_EXPAND_PROB 0.3
#define CICLOS 10

#endif //MINIPROYECTO_CONFIGS_H
